#!/bin/bash

while true; do
  read -rsn1 char

  if [[ $char == $(printf "\x1b") ]]; then
    read -rsn2 char
  fi

  case $char in
    'q') 
      reset && exit 0
    ;;
    '[A')
      printf "\x1b[1A"
    ;;
    '[B')
      printf "\x1b[1B"
    ;;
    '[D')
      printf "\x1b[1D"
    ;;
    '[C')
      printf "\x1b[1C"
    ;;
    *) printf "\x1b[2K" ;;
  esac
done
