#!/usr/local/bin/bash

clear && 
tput setaf 125 &&
(
  (
    [[ ! -z $(which toilet) ]] && 
    toilet -f pagga $(basename $(pwd))
  ) || 
  echo -e $(basename $(pwd))
) &&
tput sgr0 &&
printf "\n" &&
pwd &&
(
  (
    [[ ! -z $(which gls) ]] && 
    gls -lAhSsC --si --color=always
  ) || 
  ls -lAhSsCG
) &&
printf "\n"
