#!/bin/bash

get_num () {
  [[ ${1} =~ ^[+-]?[0-9]+([.][0-9]+)?$ ]] &&
  (( $(echo "${1} <= 1" | bc -l) )) &&
  (( $(echo "${1} > 0" | bc -l) )) &&
  echo true
}

get_url () {
  if
    [[ ! -z ${1} ]] &&
    [[ -n $(curl -s --head ${1} | head -n 1) ]]
  then
    echo ${1}
  else
    read -p 'search: ' query
    ytfzf -L ${query}
  fi
}

[[ ! -z $(get_num ${1}) ]] &&
URL=$(get_url ${2}) && [[ ! -z ${URL} ]] &&
mpv --af=rubberband=pitch-scale=${1} --speed=${1} --no-video ${URL} ||
echo -e "
usage: slomo <speed> [url]
       + speed: any decimal number between 0 and 1. 
       + url: url of file to play. opens search prompt if none specified.
"
