#!/bin/bash

isnum () {
  exp='^[+-]?[0-9]+([.][0-9]+)?$'
  ! [[ ${1} =~ ${exp} ]] && 
    echo -e "${1} is not a valid number" && 
    exit 1
}

slomo3 () {
  
  [[ ! -z "${1}" ]] &&
    url="${1}" ||
    read -p 'search: ' search
    url=$(ytfzf -L ${search})
  
  [[ ! -z "${2}" ]] &&
    speed="${2}" ||
    read -p 'speed: ' speed
  
  isnum ${speed}
  
  mpv "${url}" \
    --no-video \
    --speed="${speed}" \
    --audio-pitch-correction=no
}

slomo3 "${@}"
