#!/bin/bash

#### env

PROFILE="Profile 40"

#### utils

no-scrollback () {
  clear && printf '\e[3J'
}

#### filesystem

lw () {
  $(which "$1") "$2"
}


lx () {
  source $HOME/work/repos/myWork/shell/xp
  xp "$1"
}


la () {
  cols=$(tput cols)
  cache=$HOME/.cache/lsa/.amcache
  maxlen="$(( $cols / 6 ))"
  delim="┡"
  
  [ $cols -lt 100 ] && maxlen="$(( $cols / 3 ))"
  [ $cols -lt 65 ] && maxlen="$(( ($cols / 3) * 2 ))"

  ls -lahFG | \
  echo "$(tree -C -L 1) $(echo && pwd)" | \
  less -R
  
  no-scrollback && echo
  
  ls -A1 > $cache
  cat $cache | \
  awk '{printf("%s\n", $0)}' | \
  cut -c 1-$maxlen | \
  awk -v x=$maxlen -v d=$delim \
  '{printf(""d" %-"x"s \n", $0)}' | column
  
  echo -e "\n\ndir: $(pwd)"

  [[ "$1" =~ ^[0-9]+$ ]] && echo "$1 is a number" || echo "$1 is NOT a number";
  [ ! -z "$1" ] && echo "got $1" || echo "got nothing..."
}

#### browsers

chrome () {
  open -a "Google Chrome" \
  --args --profile-directory="Profile $PROFILE" "$@"
}


firefox () {
  /Applications/Firefox\ Developer\ Edition.app/Contents/MacOS/firefox \
  "$@" &>/dev/null &
}


####

## references:
## https://stackoverflow.com/questions/30455379/replace-every-nth-occurrence-in-huge-line-in-a-loop
## https://stackoverflow.com/questions/20348097/bash-extract-string-before-a-colon
## https://www.unix.com/shell-programming-and-scripting/257005-how-add-extra-spaces-make-all-lines-same-length.html
## https://unix.stackexchange.com/questions/283295/how-can-i-subtract-two-variables-in-bash
## https://unix.stackexchange.com/questions/151654/checking-if-an-input-number-is-an-integer

####

